services:
  - type: web
    name: telegram-news-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    environment:
      pythonVersion: 3.11.8
